### ISSUE TITLE
I found some issues with the badge frame

### ISSUE THREAD

**Issue by JermaynCodes** [iAsure/discord-arts#8]
I noticed that a 'badge frame' is not always created or it is created with excessive width. I attached a Screenshot at the end of this issue.

Here is the code snippet:

```
const buffer = await profileImage(member.id, {
        badgesFrame: true,
    });

    const attachment = new AttachmentBuilder(buffer, { name: 'welcome.png' });
```

If there is any way I can assist further, please let me know.

My Discord username is .jermayn, and I can always be reached there.

![image](https://github.com/iAsure/discord-arts/assets/67791136/bc5fab72-8081-4185-b7d2-dbc908d6ec53)

**Comment by Voroniyx** [comment]
It looks like the problem comes from checking if `badgesLength` is greater than 0 during the generation of the frame behind the badges. But since for some reason `badgesLength` is 0 for a badge, no frame is generated. I will be a deeper look into the problem and when I have found a solution then I will make a PR
